import { StyleSheet } from 'react-native';

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F7FA',
    paddingTop: 32,
  },
  searchInput: {
    backgroundColor: '#FFF',
    margin: 12,
    padding: 12,
    borderRadius: 12,
    fontSize: 14,
    elevation: 2,
  },
  card: {
    flexDirection: 'row',
    backgroundColor: '#FFF',
    marginHorizontal: 12,
    marginVertical: 6,
    borderRadius: 16,
    padding: 12,
    elevation: 3,
  },
  image: {
    width: 60,
    height: 60,
    borderRadius: 12,
    backgroundColor: '#E0E0E0',
  },
  iconTile: {
    width: 60,
    height: 60,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoContainer: {
    flex: 1,
    marginLeft: 12,
    justifyContent: 'center',
  },
  title: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1A1A1A',
  },
  subtitleRow: {
    flexDirection: 'row',
    marginTop: 4,
  },
  metaRow: {
    flexDirection: 'row',
    marginTop: 8,
  },
  description: {
    fontSize: 13,
    color: '#475569',
    marginTop: 4,
    lineHeight: 18,
  },
  categoryBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
  },
  categoryBadgeText: {
    fontSize: 12,
    fontWeight: '700',
  },
  distance: {
    fontSize: 13,
    color: '#666',
  },
  status: {
    fontSize: 13,
    marginLeft: 8,
    fontWeight: 'bold',
  },
  open: {
    color: '#2ECC71',
  },
  closed: {
    color: '#E74C3C',
  },
  loading: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
    backgroundColor: '#F5F7FA',
  },
  loadingText: {
    marginTop: 14,
    fontSize: 15,
    lineHeight: 22,
    textAlign: 'center',
    color: '#334155',
  },
  emptyState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
    backgroundColor: '#F5F7FA',
  },
  emptyListState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 40,
  },
  emptyTitle: {
    marginTop: 16,
    fontSize: 18,
    fontWeight: '700',
    color: '#0F172A',
  },
  emptyText: {
    marginTop: 10,
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
    color: '#475569',
  },
  locationCard: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 12,
    marginTop: 12,
    borderRadius: 18,
    padding: 16,
    elevation: 3,
  },
  locationCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  locationTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#0F172A',
  },
  locationText: {
    marginTop: 10,
    fontSize: 14,
    lineHeight: 20,
    color: '#475569',
  },
  errorText: {
    marginTop: 10,
    fontSize: 14,
    lineHeight: 20,
    color: '#B42318',
  },
  inlineStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginHorizontal: 12,
    marginBottom: 8,
  },
  inlineStatusText: {
    fontSize: 14,
    color: '#475569',
  },
  errorBanner: {
    marginHorizontal: 12,
    marginBottom: 8,
    fontSize: 14,
    lineHeight: 20,
    color: '#B42318',
  },
  cacheBanner: {
    marginHorizontal: 12,
    marginBottom: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    borderCurve: 'continuous',
    backgroundColor: '#FFF7ED',
    color: '#9A3412',
    fontSize: 13,
    lineHeight: 18,
  },
  listEmptyContent: {
    flexGrow: 1,
  },
});
