import { StyleSheet } from 'react-native';

export const mapStyles = StyleSheet.create({
  mapContainer: {
    flex: 1,
    backgroundColor: '#F4F8FC',
  },
  map: {
    flex: 1,
  },
  placeMarkerContainer: {
    alignItems: 'center',
  },
  placeMarkerBubble: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 6,
  },
  placeMarkerTail: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginTop: -4,
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  mapPlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    backgroundColor: '#F4F8FC',
  },
  placeholderText: {
    marginTop: 16,
    fontSize: 15,
    lineHeight: 22,
    textAlign: 'center',
    color: '#334155',
  },
  overlay: {
    position: 'absolute',
    top: 18,
    left: 18,
    right: 18,
    padding: 24,
  },
  statusCard: {
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderRadius: 18,
    padding: 16,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.14,
    shadowRadius: 18,
    elevation: 6,
  },
  statusTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0F172A',
    marginBottom: 10,
  },
  statusHint: {
    fontSize: 12,
    color: '#666666',
  },
  legendRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 12,
  },
  legendChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
  },
  legendText: {
    fontSize: 12,
    fontWeight: '700',
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 10,
    marginBottom: 10,
  },
  statusText: {
    fontSize: 14,
    color: '#334155',
    lineHeight: 20,
    marginTop: 8,
  },
  errorText: {
    fontSize: 14,
    color: '#B42318',
    lineHeight: 20,
    marginTop: 8,
  },
  cacheBanner: {
    marginTop: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    borderCurve: 'continuous',
    backgroundColor: '#FFF7ED',
    color: '#9A3412',
    fontSize: 13,
    lineHeight: 18,
  },
  buttonGroup: {
    marginTop: 12,
  },
  button: {
    backgroundColor: '#84BE12',
    paddingVertical: 10,
    borderRadius: 15,
  },
  secondaryButton: {
    backgroundColor: '#0B3C78',
    paddingVertical: 10,
    borderRadius: 15,
    marginTop: 10,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  buttonText: {
    fontSize: 14,
    color: '#ffffff',
    textAlign: 'center',
    alignContent: 'center',
  },
  secondaryButtonText: {
    fontSize: 14,
    color: '#ffffff',
    textAlign: 'center',
    alignContent: 'center',
  },
});
