import { StyleSheet } from 'react-native';

export const profileStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F6FA',
  },
  scrollContent: {
    padding: 24,
    paddingBottom: 120,
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
    fontSize: 18,
    textAlign: 'center',
    marginBottom: 20,
  },
  avatarWrapper: {
    position: 'relative',
    width: 100,
    height: 100,
    marginBottom: 12,
  },
  cameraBadge: {
    position: 'absolute',
    right: 0,
    bottom: 6,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#0B3C78',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  smallText: {
    fontSize: 13,
    textAlign: 'center',
    marginTop: 16,
    color: '#666',
    lineHeight: 18,
  },
  header: {
    alignItems: 'center',
    marginTop: 40,
  },
  avatar: {
    width: 100,
    height: 100,
    borderRadius: 50,
    marginBottom: 12,
  },
  card: {
    marginTop: 30,
    marginHorizontal: 20,
    backgroundColor: '#FFF',
    borderRadius: 12,
    padding: 24,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  spacer: {
    height: 16,
  },
  logoutContainer: {
    marginTop: 30,
    marginHorizontal: 20,
  },
  cameraContainer: {
    flex: 1,
  },
  cameraButtons: {
    position: 'absolute',
    bottom: 40,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  iconButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: 'rgba(116, 116, 116, 0.46)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  captureButton: {
    backgroundColor: '#fff',
    padding: 16,
    borderRadius: 50,
  },
  captureText: {
    fontSize: 22,
    fontWeight: 'bold',
  },
  permissionButton: {
    backgroundColor: '#222',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    marginTop: 16,
  },
  permissionButtonText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  petsContent: {
    marginTop: 30,
    marginHorizontal: 20,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 16,
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 21,
    fontWeight: '800',
    color: '#0f172a',
  },
  sectionSubtitle: {
    marginTop: 2,
    fontSize: 13,
    color: '#64748b',
  },
  addPetButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#0B3C78',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0f377a',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.22,
    shadowRadius: 10,
    elevation: 4,
  },
  emptyPetsBox: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 22,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  emptyPetsTitle: {
    marginTop: 8,
    fontSize: 17,
    fontWeight: '800',
    color: '#0f172a',
    textAlign: 'center',
  },
  emptyPetsText: {
    marginTop: 8,
    fontSize: 14,
    color: '#64748b',
    lineHeight: 20,
    textAlign: 'center',
  },
  primaryInlineButton: {
    marginTop: 16,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 10,
    backgroundColor: '#0B3C78',
  },
  primaryInlineButtonText: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  petCard: {
    flexDirection: 'row',
    gap: 14,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  petPhoto: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: '#e0f2fe',
  },
  petPhotoLarge: {
    width: 112,
    height: 112,
    borderRadius: 56,
    backgroundColor: '#e0f2fe',
  },
  petPhotoPlaceholder: {
    width: 58,
    height: 58,
    borderRadius: 29,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EAF4FF',
    borderWidth: 1,
    borderColor: '#CBE3FF',
  },
  petPhotoPlaceholderLarge: {
    width: 112,
    height: 112,
    borderRadius: 56,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EAF4FF',
    borderWidth: 1,
    borderColor: '#CBE3FF',
  },
  petCardBody: {
    flex: 1,
    minWidth: 0,
  },
  petName: {
    fontSize: 17,
    fontWeight: '800',
    color: '#0f172a',
  },
  petMeta: {
    marginTop: 4,
    fontSize: 14,
    color: '#64748b',
  },
  petActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 12,
  },
  petActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 8,
    backgroundColor: '#EEF5FF',
  },
  petActionButtonDanger: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 8,
    backgroundColor: '#FEF3F2',
  },
  petActionText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0B3C78',
  },
  petActionTextDanger: {
    fontSize: 13,
    fontWeight: '700',
    color: '#B42318',
  },
  backButton: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 12,
    paddingVertical: 8,
    paddingRight: 12,
  },
  backButtonText: {
    color: '#0B3C78',
    fontWeight: '800',
  },
  petDetailsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 20,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  petDetailsHeader: {
    alignItems: 'center',
    marginBottom: 18,
  },
  petDetailsName: {
    marginTop: 12,
    fontSize: 24,
    fontWeight: '800',
    color: '#0f172a',
    textAlign: 'center',
  },
  petDetailsMeta: {
    marginTop: 4,
    fontSize: 15,
    color: '#64748b',
    textAlign: 'center',
  },
  detailRow: {
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: '#eef2f7',
  },
  detailLabel: {
    fontSize: 13,
    color: '#64748b',
    fontWeight: '700',
  },
  detailValue: {
    marginTop: 4,
    fontSize: 16,
    color: '#0f172a',
    lineHeight: 22,
  },
  petFormCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 18,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  photoFormRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    marginTop: 18,
    marginBottom: 8,
  },
  photoButtonsColumn: {
    flex: 1,
    gap: 10,
  },
  inputLabel: {
    marginTop: 14,
    marginBottom: 6,
    fontSize: 14,
    fontWeight: '800',
    color: '#334155',
  },
  input: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 11,
    fontSize: 16,
    color: '#0f172a',
    backgroundColor: '#f8fafc',
  },
  inputError: {
    borderColor: '#B42318',
    backgroundColor: '#fff7f7',
  },
  dateInputButton: {
    width: '100%',
    minHeight: 48,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 11,
    backgroundColor: '#f8fafc',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  dateInputContent: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  dateInputText: {
    flex: 1,
    color: '#0f172a',
    fontSize: 16,
    fontWeight: '700',
  },
  dateInputPlaceholder: {
    color: '#7d8590',
    fontWeight: '500',
  },
  observacoesInput: {
    minHeight: 96,
  },
  errorText: {
    marginTop: 5,
    color: '#B42318',
    fontSize: 13,
    lineHeight: 18,
  },
  optionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  optionButton: {
    paddingVertical: 9,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    backgroundColor: '#f8fafc',
  },
  optionButtonSelected: {
    borderColor: '#0B3C78',
    backgroundColor: '#EAF4FF',
  },
  optionButtonText: {
    color: '#475569',
    fontWeight: '700',
  },
  optionButtonTextSelected: {
    color: '#0B3C78',
  },
  formActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 18,
  },
  secondaryActionButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#1f6feb',
    backgroundColor: '#eef5ff',
  },
  secondaryActionButtonText: {
    color: '#1f6feb',
    textAlign: 'center',
    fontWeight: '800',
  },
  lightActionButton: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: '#f1f5f9',
  },
  lightActionButtonText: {
    color: '#334155',
    textAlign: 'center',
    fontWeight: '800',
  },
  saveActionButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: '#0B3C78',
  },
  saveActionButtonText: {
    color: '#FFFFFF',
    textAlign: 'center',
    fontWeight: '800',
  },
  dateModalBackdrop: {
    flex: 1,
    justifyContent: 'center',
    padding: 24,
    backgroundColor: 'rgba(15, 23, 42, 0.42)',
  },
  dateModalCard: {
    width: '100%',
    maxWidth: 420,
    alignSelf: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 18,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  dateModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  dateMonthButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEF5FF',
  },
  dateModalTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '800',
    color: '#0f172a',
  },
  dateModalTitleRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  dateModalMonthText: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0f172a',
  },
  dateYearButton: {
    paddingVertical: 7,
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: '#EEF5FF',
    borderWidth: 1,
    borderColor: '#CBE3FF',
  },
  dateYearButtonText: {
    color: '#0B3C78',
    fontSize: 16,
    fontWeight: '800',
  },
  weekDaysRow: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  weekDayText: {
    width: '14.2857%',
    textAlign: 'center',
    fontSize: 12,
    fontWeight: '800',
    color: '#64748b',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  calendarDay: {
    width: '14.2857%',
    aspectRatio: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    marginVertical: 2,
  },
  calendarDaySelected: {
    backgroundColor: '#0B3C78',
  },
  calendarDayDisabled: {
    opacity: 0.34,
  },
  calendarDayText: {
    color: '#0f172a',
    fontSize: 15,
    fontWeight: '700',
  },
  calendarDayTextSelected: {
    color: '#FFFFFF',
  },
  calendarDayTextDisabled: {
    color: '#94a3b8',
  },
  yearGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  yearOption: {
    width: '31.7%',
    minHeight: 46,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  yearOptionSelected: {
    backgroundColor: '#0B3C78',
    borderColor: '#0B3C78',
  },
  yearOptionDisabled: {
    opacity: 0.34,
  },
  yearOptionText: {
    color: '#0f172a',
    fontSize: 15,
    fontWeight: '800',
  },
  yearOptionTextSelected: {
    color: '#FFFFFF',
  },
  yearOptionTextDisabled: {
    color: '#94a3b8',
  },
  dateModalActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 16,
  },
  dangerActionButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: '#FEF3F2',
    borderWidth: 1,
    borderColor: '#FDA29B',
  },
  dangerActionButtonText: {
    color: '#B42318',
    textAlign: 'center',
    fontWeight: '800',
  },
});
