import { StyleSheet } from 'react-native';

export const vaccineStyles = StyleSheet.create({
  keyboardAvoidingContainer: {
    flex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: '#F5F6FA',
  },
  scrollContent: {
    padding: 24,
    paddingBottom: 36,
  },
  headerCard: {
    marginTop: 34,
    marginBottom: 18,
    padding: 20,
    borderRadius: 18,
    backgroundColor: '#0B3C78',
    shadowColor: '#06264D',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.16,
    shadowRadius: 18,
    elevation: 6,
  },
  headerIcon: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    backgroundColor: '#84BE12',
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  headerSubtitle: {
    marginTop: 6,
    fontSize: 14,
    lineHeight: 20,
    color: '#D7E9FF',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 21,
    fontWeight: '800',
    color: '#0f172a',
  },
  sectionSubtitle: {
    marginTop: 2,
    fontSize: 13,
    color: '#64748b',
  },
  addButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#0B3C78',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0f377a',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.22,
    shadowRadius: 10,
    elevation: 4,
  },
  addButtonDisabled: {
    opacity: 0.45,
  },
  emptyBox: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 22,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  emptyTitle: {
    marginTop: 8,
    fontSize: 17,
    fontWeight: '800',
    color: '#0f172a',
    textAlign: 'center',
  },
  emptyText: {
    marginTop: 8,
    fontSize: 14,
    color: '#64748b',
    lineHeight: 20,
    textAlign: 'center',
  },
  petSelectorCard: {
    marginBottom: 20,
    padding: 14,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  petSelectorTitle: {
    marginBottom: 10,
    fontSize: 14,
    fontWeight: '800',
    color: '#334155',
  },
  petChipRow: {
    flexDirection: 'row',
    gap: 8,
  },
  petChipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  petChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minHeight: 38,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#cbd5e1',
  },
  petChipSelected: {
    backgroundColor: '#EAF4FF',
    borderColor: '#0B3C78',
  },
  petChipText: {
    color: '#475569',
    fontWeight: '800',
  },
  petChipTextSelected: {
    color: '#0B3C78',
  },
  vaccineCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 15,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  vaccineCardLate: {
    borderColor: '#FDA29B',
    backgroundColor: '#FFFBFA',
  },
  vaccineCardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  vaccineIconTile: {
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEF5FF',
  },
  vaccineCardBody: {
    flex: 1,
    minWidth: 0,
  },
  vaccineName: {
    fontSize: 17,
    fontWeight: '900',
    color: '#0f172a',
  },
  vaccinePetName: {
    marginTop: 3,
    color: '#64748b',
    fontSize: 13,
    fontWeight: '700',
  },
  statusBadge: {
    alignSelf: 'flex-start',
    paddingVertical: 5,
    paddingHorizontal: 9,
    borderRadius: 999,
  },
  statusBadgeText: {
    fontSize: 12,
    fontWeight: '900',
  },
  infoGrid: {
    marginTop: 14,
    gap: 8,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  infoLabel: {
    minWidth: 118,
    color: '#64748b',
    fontSize: 13,
    fontWeight: '800',
  },
  infoValue: {
    flex: 1,
    color: '#0f172a',
    fontSize: 14,
    lineHeight: 19,
  },
  actionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 14,
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 7,
    paddingHorizontal: 10,
    borderRadius: 8,
    backgroundColor: '#EEF5FF',
  },
  actionButtonText: {
    color: '#0B3C78',
    fontSize: 13,
    fontWeight: '800',
  },
  actionButtonDanger: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 7,
    paddingHorizontal: 10,
    borderRadius: 8,
    backgroundColor: '#FEF3F2',
  },
  actionButtonTextDanger: {
    color: '#B42318',
    fontSize: 13,
    fontWeight: '800',
  },
  formCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 18,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  formTitle: {
    fontSize: 21,
    fontWeight: '900',
    color: '#0f172a',
  },
  inputLabel: {
    marginTop: 14,
    marginBottom: 6,
    fontSize: 14,
    fontWeight: '800',
    color: '#334155',
  },
  input: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 11,
    fontSize: 16,
    color: '#0f172a',
    backgroundColor: '#f8fafc',
  },
  inputError: {
    borderColor: '#B42318',
    backgroundColor: '#fff7f7',
  },
  helperText: {
    marginTop: 5,
    color: '#64748b',
    fontSize: 12,
    lineHeight: 17,
  },
  errorText: {
    marginTop: 5,
    color: '#B42318',
    fontSize: 13,
    lineHeight: 18,
  },
  observacoesInput: {
    minHeight: 96,
  },
  formActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 18,
  },
  secondaryActionButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#1f6feb',
    backgroundColor: '#eef5ff',
  },
  secondaryActionButtonText: {
    color: '#1f6feb',
    textAlign: 'center',
    fontWeight: '800',
  },
  saveActionButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: '#0B3C78',
  },
  saveActionButtonText: {
    color: '#FFFFFF',
    textAlign: 'center',
    fontWeight: '800',
  },
  backButton: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 12,
    paddingVertical: 8,
    paddingRight: 12,
  },
  backButtonText: {
    color: '#0B3C78',
    fontWeight: '800',
  },
});
